language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - pip install -r requirements.txt
  - pip install -U setuptools wheel
  - pip install coverage

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
- python setup.py sdist bdist_wheel
- coverage run setup.py test

after_script:
  - coverage report
  - coverage xml
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi